#!/usr/bin/env node
// Fonts served by OpenCaptions itself (public/fonts/), instead of loading them from Google: no visitor's address goes
// to a third party, and the pages keep their fonts offline (local mode). This script downloads them once from Google
// Fonts with their license (all SIL Open Font License), and writes one stylesheet per font. Run it again only to update
// them; the files are committed.
//
//   node scripts/fetch-fonts.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'public', 'fonts');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'; // → woff2
const SUBSETS = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek', 'greek-ext', 'vietnamese']);

// key → stylesheet name; ofl → the font's folder in github.com/google/fonts (for its license).
const FONTS = [
  // The interface (loaded by tokens.css through brand.css).
  { key: 'atkinsonnext', css: 'brand', family: 'Atkinson+Hyperlegible+Next:ital,wght@0,400..800;1,400..800', ofl: 'atkinsonhyperlegiblenext' },
  { key: 'bricolage', css: 'brand', family: 'Bricolage+Grotesque:opsz,wght@12..96,800', ofl: 'bricolagegrotesque' },
  // Caption and reading fonts (loaded on demand by loadFont() in common.js).
  { key: 'inter', family: 'Inter:wght@400..800', ofl: 'inter' },
  { key: 'atkinson', family: 'Atkinson+Hyperlegible:wght@400;700', ofl: 'atkinsonhyperlegible' },
  { key: 'lexend', family: 'Lexend:wght@400..800', ofl: 'lexend' },
  { key: 'roboto', family: 'Roboto:wght@400..800', ofl: 'roboto' },
  { key: 'opensans', family: 'Open+Sans:wght@400..800', ofl: 'opensans' },
  { key: 'montserrat', family: 'Montserrat:wght@400..800', ofl: 'montserrat' },
];

const fetchOk = async (url) => {
  const r = await fetch(url, { headers: { 'user-agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r;
};
const getText = async (url) => (await fetchOk(url)).text();
const getFile = async (url) => Buffer.from(await (await fetchOk(url)).arrayBuffer());

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
const sheets = new Map();
const credits = [];
for (const f of FONTS) {
  const css = await getText(`https://fonts.googleapis.com/css2?family=${f.family}&display=swap`);
  const dir = path.join(OUT, f.key);
  fs.mkdirSync(dir, { recursive: true });
  const seen = new Map();
  let out = '';
  for (const [, subset, body] of css.matchAll(/\/\* ([\w-]+) \*\/\s*@font-face \{([\s\S]*?)\}/g)) {
    if (!SUBSETS.has(subset)) continue;
    const url = body.match(/url\((https:[^)]+)\)/)[1];
    if (!seen.has(url)) {
      const style = body.match(/font-style: (\w+)/)[1];
      const file = `${subset}-${style}${seen.size ? '-' + seen.size : ''}.woff2`;
      fs.writeFileSync(path.join(dir, file), await getFile(url));
      seen.set(url, file);
    }
    out += `/* ${subset} */\n@font-face {${body.replace(url, `/fonts/${f.key}/${seen.get(url)}`)}}\n`;
  }
  const license = await getText(`https://raw.githubusercontent.com/google/fonts/main/ofl/${f.ofl}/OFL.txt`);
  fs.writeFileSync(path.join(dir, 'OFL.txt'), license);
  credits.push(`| ${decodeURIComponent(f.family.split(':')[0]).replace(/\+/g, ' ')} | \`${f.key}/\` | ${license.split('\n').find((l) => /copyright/i.test(l))?.trim() || ''} |`);
  const name = f.css || f.key;
  sheets.set(name, (sheets.get(name) || '') + out);
  console.log(`✓ ${f.key}: ${seen.size} files`);
}
for (const [name, css] of sheets) fs.writeFileSync(path.join(OUT, `${name}.css`), `/* Generated by scripts/fetch-fonts.js from Google Fonts. SIL Open Font License: see each folder's OFL.txt. */\n${css}`);
fs.writeFileSync(path.join(OUT, 'README.md'), `# Fonts

Served by OpenCaptions itself, so no page loads anything from Google and the fonts work offline. Downloaded from Google Fonts by \`scripts/fetch-fonts.js\`; each folder has the font's license (SIL Open Font License 1.1), which allows using, embedding and redistributing them.

| Font | Folder | Copyright |
|---|---|---|
${credits.join('\n')}
`);
const kb = Math.round(fs.readdirSync(OUT, { recursive: true }).map((f) => path.join(OUT, String(f))).filter((f) => fs.statSync(f).isFile()).reduce((a, f) => a + fs.statSync(f).size, 0) / 1024);
console.log(`public/fonts: ${kb} KB`);
